rvm: 2.2

sudo: required
services: docker

env:
  matrix:
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-centos-66

before_install: curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 0.7.0
install: chef exec bundle install --jobs=3 --retry=3 --without='vagrant'

# https://github.com/travis-ci/travis-ci/issues/4778
before_script: sudo iptables -N DOCKER || true

script: travis_retry chef exec bundle exec rake integration:docker[${INSTANCE}]
